# ElasticSearchConnector defines settings related to ElasticSearch such as login information or URL
[ElasticSearchConnector]
    URL        = "https://elastic-search.elrond.com"
    Username   = "basic_auth_username"
    Password   = "basic_auth_password"